const colors = {
  light: {
    text: '#1A1A2E',
    tint: '#5B4FE9',
    background: '#F4F3FF',
    foreground: '#1A1A2E',
    card: '#FFFFFF',
    cardForeground: '#1A1A2E',
    primary: '#5B4FE9',
    primaryForeground: '#FFFFFF',
    secondary: '#EEF0FF',
    secondaryForeground: '#1A1A2E',
    muted: '#EEF0FF',
    mutedForeground: '#8E8EA0',
    accent: '#7C3AED',
    accentForeground: '#FFFFFF',
    destructive: '#EF4444',
    destructiveForeground: '#FFFFFF',
    border: '#E5E3F5',
    input: '#E5E3F5',
    success: '#22C55E',
    warning: '#F59E0B',
    habitColor: '#5B4FE9',
    journalColor: '#F59E0B',
    goalsColor: '#22C55E',
    remindersColor: '#EF4444',
  },
  dark: {
    text: '#F0EFFF',
    tint: '#7B6FFF',
    background: '#0E0E1A',
    foreground: '#F0EFFF',
    card: '#1A1A2E',
    cardForeground: '#F0EFFF',
    primary: '#7B6FFF',
    primaryForeground: '#FFFFFF',
    secondary: '#252538',
    secondaryForeground: '#F0EFFF',
    muted: '#252538',
    mutedForeground: '#8E8EA0',
    accent: '#9D8FFF',
    accentForeground: '#FFFFFF',
    destructive: '#EF4444',
    destructiveForeground: '#FFFFFF',
    border: '#2A2A40',
    input: '#2A2A40',
    success: '#22C55E',
    warning: '#F59E0B',
    habitColor: '#7B6FFF',
    journalColor: '#F59E0B',
    goalsColor: '#22C55E',
    remindersColor: '#EF4444',
  },
  radius: 16,
};

export default colors;
